languageCode = "en-us"
title = "mpilquist"
baseURL = "https://mpilquist.github.io/"
copyright = "Copyright (c) 2012 - 2021 Michael Pilquist"

theme = "nofancy"

[permalinks]
  post = "/blog/:year/:month/:day/:slug/"

[params]
  highlight = "solarized_dark"
  topmenu = "categories"

[author]
  name = "Michael Pilquist"
  github = "mpilquist"
  twitter = "mpilquist"
  gaID = "UA-41236326-1"

[markup.goldmark.renderer]
  unsafe = true
